# Generated by Django 5.1.6 on 2025-02-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
