# Generated by Django 5.1.6 on 2025-03-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_delete_patient_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appointments/'),
        ),
    ]
